inherit_from:
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/v1.3.0/configurations/rubocop/ruby.yml
  - http://relaxed.ruby.style/rubocop.yml

Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

